// ============================================================
// MOVIES IN THE BARN — EVENT DATA
// ============================================================
// To add a new event, copy one of the objects below and fill
// in the fields. Date format: "YYYY-MM-DD". Time: "HH:MM"
// (24-hour). posterUrl can be a full URL or a relative path
// to an image in the /images/ folder.
// ============================================================

const EVENTS = [

  // ── 2026 ────────────────────────────────────────────────

  {
    year: 2026,
    month: "April",
    theme: "Baseball & Friendship",
    title: "Eephus",
    date: "2026-04-07",
    time: "19:00",
    runtime: "99min",
    rating: "Not Rated",
    releaseYear: 2024,
    description: "Grown men's recreational baseball game stretches to extra innings on their beloved field's final day before demolition. Humor and nostalgia intertwine as daylight fades, signaling an era's end.",
    posterUrl: "images/2026/Eephus.jpg",
  },
  {
    year: 2026,
    month: "April",
    theme: "Baseball & Friendship",
    title: "Dazed and Confused",
    date: "2026-04-21",
    time: "19:00",
    runtime: "103min",
    rating: "R",
    releaseYear: 1993,
    description: "The adventures of high school and junior high students on the last day of school in May 1976.",
    posterUrl: "images/2026/Dazed and Confused.jpg",
  },
  {
    year: 2026,
    month: "May",
    theme: "Happily Ever After",
    title: "The Awful Truth",
    date: "2026-05-05",
    time: "19:00",
    runtime: "90min",
    rating: "Approved",
    releaseYear: 1937,
    description: "A married couple files an amicable divorce, but find letting go of each other harder than they originally thought.",
    posterUrl: "images/2026/The Awful Truth.jpg",
  },
  {
    year: 2026,
    month: "May",
    theme: "Happily Ever After",
    title: "Before Midnight",
    date: "2026-05-19",
    time: "19:00",
    runtime: "109min",
    rating: "R",
    releaseYear: 2013,
    description: "We meet Jesse and Celine nine years on in Greece. Almost two decades have passed since their first meeting on that train bound for Vienna.",
    posterUrl: "images/2026/Before Midnight.jpg",
  },
  {
    year: 2026,
    month: "June",
    theme: "High School Superheroes",
    title: "Chronicle",
    date: "2026-06-02",
    time: "19:00",
    runtime: "84min",
    rating: "PG-13",
    releaseYear: 2012,
    description: "Three high school friends gain superpowers after making an incredible discovery underground. Soon they find their lives spinning out of control and their bond tested as they embrace their darker sides.",
    posterUrl: "images/2026/Chronicle.jpg",
  },
  {
    year: 2026,
    month: "June",
    theme: "High School Superheroes",
    title: "Sky High",
    date: "2026-06-16",
    time: "19:00",
    runtime: "100min",
    rating: "PG",
    releaseYear: 2005,
    description: "Set in an era where superheroes are commonly known and accepted, young William Stronghold, the son of the Commander and Jetstream, tries to find a balance between being a normal teenager and an extraordinary being.",
    posterUrl: "images/2026/Sky High.jpg",
  },
  {
    year: 2026,
    month: "July",
    theme: "A Noble Criminal",
    title: "Robin Hood",
    date: "2026-07-07",
    time: "19:00",
    runtime: "83min",
    rating: "G",
    releaseYear: 1973,
    description: "The story of the legendary British outlaw portrayed with the characters as anthropomorphic animals.",
    posterUrl: "images/2026/Robin Hood.jpg",
  },
  {
    year: 2026,
    month: "July",
    theme: "A Noble Criminal",
    title: "The Princess Bride",
    date: "2026-07-21",
    time: "19:00",
    runtime: "98min",
    rating: "PG",
    releaseYear: 1987,
    description: "A bedridden boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles, enemies and allies in his quest to be reunited with his true love.",
    posterUrl: "images/2026/The Princess Bride.jpg",
  },
  {
    year: 2026,
    month: "August",
    theme: "Spies",
    title: "Mission: Impossible - Ghost Protocol",
    date: "2026-08-04",
    time: "19:00",
    runtime: "132min",
    rating: "PG-13",
    releaseYear: 2011,
    description: "The IMF is shut down when it's implicated in the bombing of the Kremlin, causing Ethan Hunt and his new team to go rogue to clear their organization's name.",
    posterUrl: "images/2026/Mission_ Impossible - Ghost Protocol.jpg",
  },
  {
    year: 2026,
    month: "August",
    theme: "Spies",
    title: "RED",
    date: "2026-08-25",
    time: "19:00",
    runtime: "111min",
    rating: "PG-13",
    releaseYear: 2010,
    description: "When his peaceful life is threatened by a high-tech assassin, former black-ops agent Frank Moses reassembles his old team in a last-ditch effort to survive and uncover the assailants.",
    posterUrl: "images/2026/Red.jpg",
  },
  {
    year: 2026,
    month: "September",
    theme: "Musicals Go West",
    title: "Seven Brides for Seven Brothers",
    date: "2026-09-01",
    time: "19:00",
    runtime: "102min",
    rating: "Approved",
    releaseYear: 1954,
    description: "When a backwoodsman in 1850s Oregon brings a wife home to his farm, his six brothers decide that they want to get married too.",
    posterUrl: "images/2026/Seven Brides for Seven Brothers.jpg",
  },
  {
    year: 2026,
    month: "September",
    theme: "Musicals Go West",
    title: "Annie Get Your Gun",
    date: "2026-09-15",
    time: "19:00",
    runtime: "107min",
    rating: "Approved",
    releaseYear: 1950,
    description: "The story of the great sharpshooter Annie Oakley, who rose to fame while dealing with her love/professional rival, Frank Butler.",
    posterUrl: "images/2026/Annie Get Your Gun.jpg",
  },
  {
    year: 2026,
    month: "October",
    theme: "The Not Too Distant Future",
    title: "Exam",
    date: "2026-10-06",
    time: "19:00",
    runtime: "101min",
    rating: "Not Rated",
    releaseYear: 2009,
    description: "Eight candidates for a highly desirable corporate job are locked together in an exam room and given a final test with just one seemingly simple question.",
    posterUrl: "images/2026/Exam.jpg",
  },
  {
    year: 2026,
    month: "October",
    theme: "The Not Too Distant Future",
    title: "Gattaca",
    date: "2026-10-20",
    time: "19:00",
    runtime: "106min",
    rating: "PG-13",
    releaseYear: 1997,
    description: "Vincent, an \"In-Valid,\" assumes the identity of a member of the genetic elite to pursue his goal of traveling into space with the Gattaca Aerospace Corporation.",
    posterUrl: "images/2026/Gattaca.jpg",
  },
  {
    year: 2026,
    month: "November",
    theme: "Innovation & Ego",
    title: "BlackBerry",
    date: "2026-11-03",
    time: "19:00",
    runtime: "120min",
    rating: "R",
    releaseYear: 2023,
    description: "The story of the meteoric rise and catastrophic demise of the world's first smartphone.",
    posterUrl: "images/2026/BlackBerry.jpg",
  },
  {
    year: 2026,
    month: "November",
    theme: "Innovation & Ego",
    title: "Steve Jobs",
    date: "2026-11-17",
    time: "19:00",
    runtime: "122min",
    rating: "R",
    releaseYear: 2015,
    description: "Steve Jobs takes us behind the scenes of the digital revolution, to paint a portrait of the man at its epicenter.",
    posterUrl: "images/2026/Steve Jobs.jpg",
  },

  // ── 2025 ────────────────────────────────────────────────

  {
    year: 2025,
    month: "April",
    theme: "Love & Food",
    title: "The Taste of Things",
    date: "2025-04-01",
    time: "19:00",
    runtime: "135min",
    rating: "PG-13",
    releaseYear: 2023,
    description: "The story of Eugenie, an esteemed cook, and Dodin - the fine gourmet chef she has been working for over the last 20 years.",
    posterUrl: "images/2025/The Taste of Things.jpg",
  },
  {
    year: 2025,
    month: "April",
    theme: "Love & Food",
    title: "Babette's Feast",
    date: "2025-04-22",
    time: "19:00",
    runtime: "103min",
    rating: "G",
    releaseYear: 1987,
    description: "During the late 19th century, a strict religious community in a Danish village takes in a French refugee from the Franco-Prussian War as a servant to the late pastor's daughters.",
    posterUrl: "images/2025/Babette's Feast.jpg",
  },
  {
    year: 2025,
    month: "May",
    theme: "We Meet Again",
    title: "An Affair to Remember",
    date: "2025-05-06",
    time: "19:00",
    runtime: "115min",
    rating: "Approved",
    releaseYear: 1957,
    description: "A couple falls in love and agrees to meet in six months at the Empire State Building - but will it happen?",
    posterUrl: "images/2025/An Affair to Remember.jpg",
  },
  {
    year: 2025,
    month: "May",
    theme: "We Meet Again",
    title: "Before Sunset",
    date: "2025-05-20",
    time: "19:00",
    runtime: "80min",
    rating: "R",
    releaseYear: 2004,
    description: "Nine years after Jesse and Celine first met, they encounter each other again on the French leg of Jesse's book tour.",
    posterUrl: "images/2025/Before Sunset.jpg",
  },
  {
    year: 2025,
    month: "June",
    theme: "King of the Monsters",
    title: "Godzilla",
    date: "2025-06-03",
    time: "19:00",
    runtime: "96min",
    rating: "Not Rated",
    releaseYear: 1954,
    description: "After a dinosaur-like beast - awoken from undersea hibernation by atom bomb testing - ravages Tokyo, a scientist must decide if his similarly dangerous weapon should be used to destroy it.",
    posterUrl: "images/2025/Godzilla.jpg",
  },
  {
    year: 2025,
    month: "June",
    theme: "King of the Monsters",
    title: "Godzilla Minus One",
    date: "2025-06-17",
    time: "19:00",
    runtime: "124min",
    rating: "PG-13",
    releaseYear: 2023,
    description: "Post-war Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.",
    posterUrl: "images/2025/Godzilla Minus One.jpg",
  },
  {
    year: 2025,
    month: "July",
    theme: "Disney Goes Sci-Fi",
    title: "Lilo & Stitch",
    date: "2025-07-08",
    time: "19:00",
    runtime: "85min",
    rating: "PG",
    releaseYear: 2002,
    description: "A young and parentless girl adopts a 'dog' from the local pound, completely unaware that it's supposedly a dangerous scientific experiment that's taken refuge on Earth and is now hiding from its creator and those who see it as a menace.",
    posterUrl: "images/2025/Lilo and Stitch.jpg",
  },
  {
    year: 2025,
    month: "July",
    theme: "Disney Goes Sci-Fi",
    title: "Treasure Planet",
    date: "2025-07-22",
    time: "19:00",
    runtime: "95min",
    rating: "PG",
    releaseYear: 2002,
    description: "Jim Hawkins is a teenager who finds the map of a great treasure hidden by a space pirate. Together with some friends, he sets off in a large spaceship, shaped like a caravel, on his quest.",
    posterUrl: "images/2025/Treasure Planet.jpg",
  },
  {
    year: 2025,
    month: "August",
    theme: "Misfits",
    title: "Sing Street",
    date: "2025-08-12",
    time: "19:00",
    runtime: "106min",
    rating: "PG-13",
    releaseYear: 2016,
    description: "A young lad notices a beautiful girl who begins to occupy his thoughts. While struggling with poverty, personal relationships and life's woes, he starts a band, hoping to catch her attention.",
    posterUrl: "images/2025/Sing Street.jpg",
  },
  {
    year: 2025,
    month: "August",
    theme: "Misfits",
    title: "Moonrise Kingdom",
    date: "2025-08-26",
    time: "19:00",
    runtime: "94min",
    rating: "PG-13",
    releaseYear: 2012,
    description: "Two 12-year-olds, who live on an island, fall in love with each other and elope into the wilderness. While people set out on a search mission, a violent storm approaching them catches their attention.",
    posterUrl: "images/2025/Moonrise Kingdom.jpg",
  },
  {
    year: 2025,
    month: "September",
    theme: "Raising Kids",
    title: "The Florida Project",
    date: "2025-09-16",
    time: "19:00",
    runtime: "111min",
    rating: "R",
    releaseYear: 2017,
    description: "A single mother and the manager of a roadside motel do their utmost to maintain the innocence of a six-year-old girl's life.",
    posterUrl: "images/2025/The Florida Project.jpg",
  },
  {
    year: 2025,
    month: "September",
    theme: "Raising Kids",
    title: "Daddy Longlegs",
    date: "2025-09-30",
    time: "19:00",
    runtime: "100min",
    rating: "Not Rated",
    releaseYear: 2009,
    description: "A father juggling his kids with the rest of his responsibilities is ultimately faced with the choice of being their father or their friend.",
    posterUrl: "images/2025/Daddy Longlegs.jpg",
  },
  {
    year: 2025,
    month: "October",
    theme: "A Monster Who Sings",
    title: "Phantom of the Paradise",
    date: "2025-10-17",
    time: "19:00",
    runtime: "91min",
    rating: "PG",
    releaseYear: 1974,
    description: "A disfigured composer sells his soul for the woman he loves so that she will perform his music. However, an evil record tycoon betrays him and steals his music to open his rock palace, The Paradise.",
    posterUrl: "images/2025/Phantom of the Paradise.jpg",
  },
  {
    year: 2025,
    month: "October",
    theme: "A Monster Who Sings",
    title: "Little Shop of Horrors",
    date: "2025-10-28",
    time: "19:00",
    runtime: "94min",
    rating: "PG-13",
    releaseYear: 1986,
    description: "A nerdy florist finds his chance for success and romance with the help of a giant man-eating plant who demands to be fed.",
    posterUrl: "images/2025/Little Shop of Horrors.jpg",
  },
  {
    year: 2025,
    month: "November",
    theme: "Hostages",
    title: "Patty Hearst",
    date: "2025-11-11",
    time: "19:00",
    runtime: "108min",
    rating: "R",
    releaseYear: 1988,
    description: "In the 1970s, Patricia Hearst is abducted by American revolutionaries, but eventually joins their cause instead.",
    posterUrl: "images/2025/Patty Hearst.jpg",
  },
  {
    year: 2025,
    month: "November",
    theme: "Hostages",
    title: "Inside Man",
    date: "2025-11-25",
    time: "19:00",
    runtime: "129min",
    rating: "R",
    releaseYear: 2006,
    description: "A police detective, a bank robber, and a high-power broker enter high-stakes negotiations after the criminal's brilliant heist spirals into a hostage situation.",
    posterUrl: "images/2025/Inside Man.jpg",
  },

  // ── 2024 ────────────────────────────────────────────────

  {
    year: 2024,
    month: "April",
    theme: "The Truth",
    title: "Anatomy of a Fall",
    date: "2024-04-16",
    time: "19:00",
    runtime: "151min",
    rating: "R",
    releaseYear: 2023,
    description: "A woman is suspected of murder after her husband's death; their half-blind son faces a moral dilemma as the main witness.",
    posterUrl: "images/2024/Anatomy of a Fall.jpg",
  },
  {
    year: 2024,
    month: "April",
    theme: "The Truth",
    title: "The Last Duel",
    date: "2024-04-30",
    time: "19:00",
    runtime: "152min",
    rating: "R",
    releaseYear: 2021,
    description: "The Knight Jean de Carrouges must settle the dispute over his wife Marguerite by challenging his former friend to a duel to the death.",
    posterUrl: "images/2024/The Last Duel.jpg",
  },
  {
    year: 2024,
    month: "May",
    theme: "A Chance Encounter",
    title: "Love Affair",
    date: "2024-05-14",
    time: "19:00",
    runtime: "88min",
    rating: "Approved",
    releaseYear: 1939,
    description: "A French playboy and an American former nightclub singer fall in love aboard a ship.",
    posterUrl: "images/2024/Love Affair.jpg",
  },
  {
    year: 2024,
    month: "May",
    theme: "A Chance Encounter",
    title: "Before Sunrise",
    date: "2024-05-28",
    time: "19:00",
    runtime: "101min",
    rating: "R",
    releaseYear: 1995,
    description: "A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna.",
    posterUrl: "images/2024/Before Sunrise.jpg",
  },
  {
    year: 2024,
    month: "June",
    theme: "Mothers & Daughters",
    title: "Whip It",
    date: "2024-06-11",
    time: "19:00",
    runtime: "111min",
    rating: "PG-13",
    releaseYear: 2009,
    description: "In Bodeen, Texas, an indie-rock-loving misfit finds a way of dealing with small-town misery after discovering a roller-derby league in nearby Austin.",
    posterUrl: "images/2024/Whip It.jpg",
  },
  {
    year: 2024,
    month: "June",
    theme: "Mothers & Daughters",
    title: "Lady Bird",
    date: "2024-06-25",
    time: "19:00",
    runtime: "94min",
    rating: "R",
    releaseYear: 2017,
    description: "In 2002, an artistically inclined 17-year-old girl comes of age in Sacramento, California.",
    posterUrl: "images/2024/Lady Bird.jpg",
  },
  {
    year: 2024,
    month: "July",
    theme: "Fox & the Henhouse",
    title: "Fantastic Mr. Fox",
    date: "2024-07-16",
    time: "19:00",
    runtime: "87min",
    rating: "PG",
    releaseYear: 2009,
    description: "An urbane fox cannot resist returning to his farm raiding ways and then must help his community survive the farmers' retaliation.",
    posterUrl: "images/2024/Fantastic Mr. Fox.jpg",
  },
  {
    year: 2024,
    month: "July",
    theme: "Fox & the Henhouse",
    title: "Chicken Run",
    date: "2024-07-30",
    time: "19:00",
    runtime: "84min",
    rating: "G",
    releaseYear: 2000,
    description: "When a cockerel apparently flies into a chicken farm, the chickens see him as an opportunity to escape their evil owners.",
    posterUrl: "images/2024/Chicken Run.jpg",
  },
  {
    year: 2024,
    month: "August",
    theme: "Scoundrels",
    title: "Guardians of the Galaxy",
    date: "2024-08-14",
    time: "19:00",
    runtime: "121min",
    rating: "PG-13",
    releaseYear: 2014,
    description: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    posterUrl: "images/2024/Guardians of the Galaxy.jpg",
  },
  {
    year: 2024,
    month: "August",
    theme: "Scoundrels",
    title: "Dungeons & Dragons: Honor Among Thieves",
    date: "2024-08-27",
    time: "19:00",
    runtime: "134min",
    rating: "PG-13",
    releaseYear: 2023,
    description: "A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a lost relic.",
    posterUrl: "images/2024/Dungeons & Dragons.jpg",
  },
  {
    year: 2024,
    month: "September",
    theme: "The Presleys",
    title: "Elvis",
    date: "2024-09-17",
    time: "19:00",
    runtime: "159min",
    rating: "PG-13",
    releaseYear: 2022,
    description: "The life of American music icon Elvis Presley, from his childhood to becoming a rock and movie star in the 1950s.",
    posterUrl: "images/2024/Elvis.jpg",
  },
  {
    year: 2024,
    month: "September",
    theme: "The Presleys",
    title: "Priscilla",
    date: "2024-10-01",
    time: "19:00",
    runtime: "113min",
    rating: "R",
    releaseYear: 2023,
    description: "When teenage Priscilla Beaulieu meets Elvis Presley, the man who is already a meteoric rock-and-roll superstar becomes someone entirely unexpected in private moments.",
    posterUrl: "images/2024/Priscilla.jpg",
  },
  {
    year: 2024,
    month: "October",
    theme: "Scares & Laughs",
    title: "The Witches of Eastwick",
    date: "2024-10-15",
    time: "19:00",
    runtime: "118min",
    rating: "R",
    releaseYear: 1987,
    description: "Three single women in a picturesque village have their wishes granted, at a cost, when a mysterious and flamboyant man arrives in their lives.",
    posterUrl: "images/2024/The Witches of Eastwick.jpg",
  },
  {
    year: 2024,
    month: "October",
    theme: "Scares & Laughs",
    title: "Death Becomes Her",
    date: "2024-10-29",
    time: "19:00",
    runtime: "104min",
    rating: "PG-13",
    releaseYear: 1992,
    description: "When a fading actress learns of an immortality treatment, she sees it as a way to outdo her long-time rival.",
    posterUrl: "images/2024/Death Becomes Her.jpg",
  },
  {
    year: 2024,
    month: "November",
    theme: "Adult Friendship",
    title: "Digging for Fire",
    date: "2024-11-12",
    time: "19:00",
    runtime: "85min",
    rating: "R",
    releaseYear: 2015,
    description: "The discovery of a bone and a gun send a husband and wife on separate adventures over the course of a weekend.",
    posterUrl: "images/2024/Digging for Fire.jpg",
  },
  {
    year: 2024,
    month: "November",
    theme: "Adult Friendship",
    title: "While We're Young",
    date: "2024-11-26",
    time: "19:00",
    runtime: "97min",
    rating: "R",
    releaseYear: 2014,
    description: "A middle-aged couple's career and marriage are overturned when a disarming young couple enters their lives.",
    posterUrl: "images/2024/While We're Young.jpg",
  },

  // ── 2023 ────────────────────────────────────────────────

  {
    year: 2023,
    month: "April",
    theme: "Fascism (with Style)",
    title: "RRR",
    date: "2023-04-18",
    time: "19:00",
    runtime: "187min",
    rating: "Not Rated",
    releaseYear: 2022,
    description: "A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.",
    posterUrl: "images/2023/RRR.jpg",
  },
  {
    year: 2023,
    month: "April",
    theme: "Fascism (with Style)",
    title: "The Grand Budapest Hotel",
    date: "2023-05-02",
    time: "19:00",
    runtime: "99min",
    rating: "R",
    releaseYear: 2014,
    description: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
    posterUrl: "images/2023/The Grand Budapest Hotel.jpg",
  },
  {
    year: 2023,
    month: "May",
    theme: "Unorthodox Education",
    title: "Captain Fantastic",
    date: "2023-05-16",
    time: "19:00",
    runtime: "118min",
    rating: "R",
    releaseYear: 2016,
    description: "In the forests of the Pacific Northwest, a father devoted to raising his six kids with a rigorous physical and intellectual education is forced to leave his paradise and enter the world.",
    posterUrl: "images/2023/Captain Fantastic.jpg",
  },
  {
    year: 2023,
    month: "May",
    theme: "Unorthodox Education",
    title: "Gifted",
    date: "2023-05-30",
    time: "19:00",
    runtime: "101min",
    rating: "PG-13",
    releaseYear: 2017,
    description: "Frank, a single man raising his child prodigy niece Mary, is drawn into a custody battle with his mother.",
    posterUrl: "images/2023/Gifted.jpg",
  },
  {
    year: 2023,
    month: "June",
    theme: "High School",
    title: "Brick",
    date: "2023-06-13",
    time: "19:00",
    runtime: "110min",
    rating: "R",
    releaseYear: 2005,
    description: "A teenage loner pushes his way into the underworld of a high school crime ring to investigate the disappearance of his ex-girlfriend.",
    posterUrl: "images/2023/Brick.jpg",
  },
  {
    year: 2023,
    month: "June",
    theme: "High School",
    title: "Donnie Darko",
    date: "2023-06-27",
    time: "19:00",
    runtime: "113min",
    rating: "R",
    releaseYear: 2001,
    description: "After narrowly escaping a bizarre accident, a troubled teenager is plagued by visions of a man in a large rabbit suit who manipulates him to commit a series of crimes.",
    posterUrl: "images/2023/Donnie Darko.png",
  },
  {
    year: 2023,
    month: "July",
    theme: "Car, Boy, Girl",
    title: "The Love Bug",
    date: "2023-07-18",
    time: "19:00",
    runtime: "108min",
    rating: "G",
    releaseYear: 1968,
    description: "Down-on-his-luck race car driver Jim Douglas teams up with a little VW Bug that has a mind of its own.",
    posterUrl: "images/2023/The Love Bug.jpg",
  },
  {
    year: 2023,
    month: "July",
    theme: "Car, Boy, Girl",
    title: "Herbie Fully Loaded",
    date: "2023-08-01",
    time: "19:00",
    runtime: "101min",
    rating: "G",
    releaseYear: 2005,
    description: "Maggie Peyton, the new owner of Herbie, the free-wheelin' Volkswagen bug with a mind of its own, puts the car through its paces on the road to becoming a NASCAR competitor.",
    posterUrl: "images/2023/Herbie Fully Loaded.jpg",
  },
  {
    year: 2023,
    month: "August",
    theme: "Heist at the Racetrack",
    title: "Logan Lucky",
    date: "2023-08-15",
    time: "19:00",
    runtime: "118min",
    rating: "PG-13",
    releaseYear: 2017,
    description: "Two brothers attempt to pull off a heist during a NASCAR race in North Carolina.",
    posterUrl: "images/2023/Logan Lucky.jpg",
  },
  {
    year: 2023,
    month: "August",
    theme: "Heist at the Racetrack",
    title: "The Killing",
    date: "2023-08-29",
    time: "19:00",
    runtime: "84min",
    rating: "Approved",
    releaseYear: 1956,
    description: "Crook Johnny Clay assembles a five-man team to plan and execute a daring racetrack robbery.",
    posterUrl: "images/2023/The Killing.jpg",
  },
  {
    year: 2023,
    month: "September",
    theme: "A Youthful Connection",
    title: "Cha Cha Real Smooth",
    date: "2023-09-19",
    time: "19:00",
    runtime: "107min",
    rating: "R",
    releaseYear: 2022,
    description: "A young man who works as a Bar Mitzvah party host strikes up a friendship with a mother and her autistic daughter.",
    posterUrl: "images/2023/Cha Cha Real Smooth.jpg",
  },
  {
    year: 2023,
    month: "September",
    theme: "A Youthful Connection",
    title: "Tully",
    date: "2023-10-03",
    time: "19:00",
    runtime: "95min",
    rating: "R",
    releaseYear: 2018,
    description: "A struggling mother of three forms an unexpected bond with the night nanny hired to help with her newborn baby.",
    posterUrl: "images/2023/Tully.jpg",
  },
  {
    year: 2023,
    month: "October",
    theme: "Not Who They Seem",
    title: "Get Out",
    date: "2023-10-17",
    time: "19:00",
    runtime: "104min",
    rating: "R",
    releaseYear: 2017,
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
    posterUrl: "images/2023/Get Out.jpg",
  },
  {
    year: 2023,
    month: "October",
    theme: "Not Who They Seem",
    title: "The Thing",
    date: "2023-10-31",
    time: "19:00",
    runtime: "109min",
    rating: "R",
    releaseYear: 1982,
    description: "A team of American scientists investigate the empty, destroyed base of their Norwegian counterparts in Antarctica, only to discover a terrifying life force that can take the form of its prey.",
    posterUrl: "images/2023/The Thing.jpg",
  },
  {
    year: 2023,
    month: "November",
    theme: "Following Orders",
    title: "Paths of Glory",
    date: "2023-11-14",
    time: "19:00",
    runtime: "88min",
    rating: "Approved",
    releaseYear: 1957,
    description: "After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them.",
    posterUrl: "images/2023/Paths of Glory.jpg",
  },
  {
    year: 2023,
    month: "November",
    theme: "Following Orders",
    title: "A Few Good Men",
    date: "2023-11-28",
    time: "19:00",
    runtime: "138min",
    rating: "R",
    releaseYear: 1992,
    description: "Military lawyer Lieutenant Daniel Kaffee defends Marines accused of murder, who contend they were acting under orders.",
    posterUrl: "images/2023/A Few Good Men.jpg",
  },

  // ── 2022 ────────────────────────────────────────────────

  {
    year: 2022,
    month: "April",
    theme: "Marriage, Children, & Jealousy",
    title: "Annette",
    date: "2022-04-13",
    time: "19:00",
    runtime: "141min",
    rating: "R",
    releaseYear: 2021,
    description: "A stand-up comedian and his opera singer wife have a two-year-old daughter with a surprising gift.",
    posterUrl: "images/2022/Annette.jpg",
  },
  {
    year: 2022,
    month: "April",
    theme: "Marriage, Children, & Jealousy",
    title: "Marriage Story",
    date: "2022-04-27",
    time: "19:00",
    runtime: "137min",
    rating: "R",
    releaseYear: 2019,
    description: "A stage director and an actress struggle through a grueling, coast-to-coast divorce that pushes them to their personal extremes.",
    posterUrl: "images/2022/Marriage Story.jpg",
  },
  {
    year: 2022,
    month: "May",
    theme: "The Cold War",
    title: "The Shape of Water",
    date: "2022-05-11",
    time: "19:00",
    runtime: "123min",
    rating: "R",
    releaseYear: 2017,
    description: "At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.",
    posterUrl: "images/2022/The Shape of Water.jpg",
  },
  {
    year: 2022,
    month: "May",
    theme: "The Cold War",
    title: "The Iron Giant",
    date: "2022-05-25",
    time: "19:00",
    runtime: "86min",
    rating: "PG",
    releaseYear: 1999,
    description: "In the small town of Rockwell, Maine in October 1957, a giant metal machine befriends a nine-year-old boy and ultimately finds its humanity.",
    posterUrl: "images/2022/The Iron Giant.jpg",
  },
  {
    year: 2022,
    month: "June",
    theme: "Future Cult Classics",
    title: "Scott Pilgrim vs. the World",
    date: "2022-06-08",
    time: "19:00",
    runtime: "112min",
    rating: "PG-13",
    releaseYear: 2010,
    description: "Scott Pilgrim is a 23 year old radical Canadian gamer and wannabe rockstar who falls in love with an American delivery girl and must defeat her seven evil exes.",
    posterUrl: "images/2022/Scott Pilgrim vs. the World.jpg",
  },
  {
    year: 2022,
    month: "June",
    theme: "Future Cult Classics",
    title: "Everybody Wants Some!!",
    date: "2022-06-18",
    time: "19:00",
    runtime: "117min",
    rating: "R",
    releaseYear: 2016,
    description: "A comedy that follows a group of friends as they navigate their way through the freedoms and responsibilities of unsupervised adulthood.",
    posterUrl: "images/2022/Everybody Wants Some.jpg",
  },
  {
    year: 2022,
    month: "July",
    theme: "Overly Ambitious Sci-Fi",
    title: "Speed Racer",
    date: "2022-07-06",
    time: "19:00",
    runtime: "135min",
    rating: "PG",
    releaseYear: 2008,
    description: "Speed Racer is the tale of a young and brilliant racing driver who must team up with the police and the mysterious Racer X to bring an end to racing corruption.",
    posterUrl: "images/2022/Speed Racer.jpg",
  },
  {
    year: 2022,
    month: "July",
    theme: "Overly Ambitious Sci-Fi",
    title: "Valerian and the City of a Thousand Planets",
    date: "2022-07-27",
    time: "19:00",
    runtime: "136min",
    rating: "PG-13",
    releaseYear: 2017,
    description: "A dark force threatens Alpha, a vast metropolis and home to species from a thousand planets. Special operatives Valerian and Laureline must race to identify the marauding menace.",
    posterUrl: "images/2022/Valerian and the City of a Thousand Planets.jpg",
  },
  {
    year: 2022,
    month: "August",
    theme: "Musicians in Over Their Heads",
    title: "Ishtar",
    date: "2022-08-10",
    time: "19:00",
    runtime: "107min",
    rating: "PG-13",
    releaseYear: 1987,
    description: "Two terrible lounge singers get booked to play a gig in a Moroccan hotel but somehow become pawns in an international power play.",
    posterUrl: "images/2022/Ishtar.jpg",
  },
  {
    year: 2022,
    month: "August",
    theme: "Musicians in Over Their Heads",
    title: "O Brother, Where Art Thou?",
    date: "2022-08-24",
    time: "19:00",
    runtime: "107min",
    rating: "PG-13",
    releaseYear: 2000,
    description: "In the deep south during the 1930s, three escaped convicts search for hidden treasure while a relentless lawman pursues them.",
    posterUrl: "images/2022/O Brother, Where Art Thou.jpg",
  },
  {
    year: 2022,
    month: "September",
    theme: "The Civil War",
    title: "Little Women",
    date: "2022-09-14",
    time: "19:00",
    runtime: "145min",
    rating: "PG",
    releaseYear: 2019,
    description: "Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.",
    posterUrl: "images/2022/Little Women.jpg",
  },
  {
    year: 2022,
    month: "September",
    theme: "The Civil War",
    title: "The Beguiled",
    date: "2022-09-28",
    time: "19:00",
    runtime: "93min",
    rating: "R",
    releaseYear: 2017,
    description: "The unexpected arrival of a wounded Union soldier at a girls school in Virginia during the American Civil War leads to jealousy and betrayal.",
    posterUrl: "images/2022/The Beguiled.jpg",
  },
  {
    year: 2022,
    month: "October",
    theme: "Identity in Sports",
    title: "The Rider",
    date: "2022-10-12",
    time: "19:00",
    runtime: "104min",
    rating: "R",
    releaseYear: 2017,
    description: "After suffering a near fatal head injury, a young cowboy undertakes a search for new identity and what it means to be a man in the heartland of America.",
    posterUrl: "images/2022/The Rider.jpg",
  },
  {
    year: 2022,
    month: "October",
    theme: "Identity in Sports",
    title: "Nadia, Butterfly",
    date: "2022-10-26",
    time: "19:00",
    runtime: "107min",
    rating: "Not Rated",
    releaseYear: 2020,
    description: "Nadia, an Olympic swimmer in her twenties, faces the challenges of her imminent retirement.",
    posterUrl: "images/2022/Nadia, Butterfly.jpg",
  },
  {
    year: 2022,
    month: "November",
    theme: "Los Angeles: 1969-1970",
    title: "Once Upon a Time... in Hollywood",
    date: "2022-11-09",
    time: "19:00",
    runtime: "161min",
    rating: "R",
    releaseYear: 2019,
    description: "A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles.",
    posterUrl: "images/2022/Once Upon a Time... in Hollywood.jpg",
  },
  {
    year: 2022,
    month: "November",
    theme: "Los Angeles: 1969-1970",
    title: "Inherent Vice",
    date: "2022-11-23",
    time: "19:00",
    runtime: "148min",
    rating: "R",
    releaseYear: 2014,
    description: "In 1970, drug-fueled Los Angeles private investigator Larry \"Doc\" Sportello investigates the disappearance of a former girlfriend.",
    posterUrl: "images/2022/Inherent Vice.jpg",
  },

  // ── 2021 ────────────────────────────────────────────────

  {
    year: 2021,
    month: "May",
    theme: "Journalism",
    title: "Shattered Glass",
    date: "2021-05-12",
    time: "19:00",
    runtime: "94min",
    rating: "PG-13",
    releaseYear: 2003,
    description: "The story of a young journalist who fell from grace when it was discovered he fabricated over half of his articles.",
    posterUrl: "images/2021/Shattered Glass.jpg",
  },
  {
    year: 2021,
    month: "May",
    theme: "Journalism",
    title: "Nightcrawler",
    date: "2021-05-26",
    time: "19:00",
    runtime: "117min",
    rating: "R",
    releaseYear: 2014,
    description: "When Louis Bloom, a con man desperate for work, muscles into the world of L.A. crime journalism, he blurs the line between observer and participant.",
    posterUrl: "images/2021/Nightcrawler.jpg",
  },
  {
    year: 2021,
    month: "June",
    theme: "Apocalypse",
    title: "The Road Warrior",
    date: "2021-06-09",
    time: "19:00",
    runtime: "96min",
    rating: "R",
    releaseYear: 1981,
    description: "In the post-apocalyptic Australian wasteland, a cynical drifter agrees to help a small, gasoline-rich community escape a horde of bandits.",
    posterUrl: "images/2021/Mad Max 2.jpg",
  },
  {
    year: 2021,
    month: "June",
    theme: "Apocalypse",
    title: "Snowpiercer",
    date: "2021-06-23",
    time: "19:00",
    runtime: "126min",
    rating: "R",
    releaseYear: 2013,
    description: "In a future where a failed climate change experiment has killed all life except for the survivors who boarded the Snowpiercer, a new class system emerges.",
    posterUrl: "images/2021/Snowpiercer.jpg",
  },
  {
    year: 2021,
    month: "July",
    theme: "The Stage",
    title: "Me and Orson Welles",
    date: "2021-07-14",
    time: "19:00",
    runtime: "114min",
    rating: "PG-13",
    releaseYear: 2008,
    description: "In 1937, a teenager is cast in the Mercury Theatre production of \"Julius Caesar\", directed by a young Orson Welles.",
    posterUrl: "images/2021/Me and Orson Welles.jpg",
  },
  {
    year: 2021,
    month: "July",
    theme: "The Stage",
    title: "I Wanna Hold Your Hand",
    date: "2021-07-28",
    time: "19:00",
    runtime: "104min",
    rating: "PG",
    releaseYear: 1978,
    description: "In 1964, six teenagers from New Jersey run off to see The Beatles perform on Ed Sullivan in the hope of meeting their idols.",
    posterUrl: "images/2021/I Wanna Hold Your Hand.jpg",
  },
  {
    year: 2021,
    month: "August",
    theme: "Corruption",
    title: "A Most Violent Year",
    date: "2021-08-11",
    time: "19:00",
    runtime: "125min",
    rating: "R",
    releaseYear: 2014,
    description: "In New York City 1981, an ambitious immigrant fights to protect his business and family during the most dangerous year in the city's history.",
    posterUrl: "images/2021/A Most Violent Year.jpg",
  },
  {
    year: 2021,
    month: "August",
    theme: "Corruption",
    title: "Allied",
    date: "2021-08-25",
    time: "19:00",
    runtime: "124min",
    rating: "R",
    releaseYear: 2016,
    description: "In 1942, a Canadian intelligence officer in North Africa encounters a female French Resistance fighter on a deadly mission behind enemy lines.",
    posterUrl: "images/2021/Allied.jpg",
  },
  {
    year: 2021,
    month: "September",
    theme: "The Class Divide",
    title: "Parasite",
    date: "2021-09-08",
    time: "19:00",
    runtime: "132min",
    rating: "R",
    releaseYear: 2019,
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    posterUrl: "images/2021/Parasite.jpg",
  },
  {
    year: 2021,
    month: "September",
    theme: "The Class Divide",
    title: "Dead Pigs",
    date: "2021-09-22",
    time: "19:00",
    runtime: "122min",
    rating: "Not Rated",
    releaseYear: 2018,
    description: "A bumbling pig farmer, a feisty salon owner, a sensitive busboy, an expat architect and a disenchanted rich girl converge as thousands of dead pigs float down the river toward a rapidly-modernizing Shanghai.",
    posterUrl: "images/2021/Dead Pigs.jpg",
  },
  {
    year: 2021,
    month: "October",
    theme: "Vampires!",
    title: "The Lost Boys",
    date: "2021-10-13",
    time: "19:00",
    runtime: "97min",
    rating: "R",
    releaseYear: 1987,
    description: "After moving to a new town, two brothers discover that the area is a haven for vampires.",
    posterUrl: "images/2021/The Lost Boys.jpg",
  },
  {
    year: 2021,
    month: "October",
    theme: "Vampires!",
    title: "What We Do in the Shadows",
    date: "2021-10-27",
    time: "19:00",
    runtime: "86min",
    rating: "R",
    releaseYear: 2014,
    description: "Viago, Deacon, and Vladislav are vampires who are struggling with the mundane aspects of modern life, like paying rent, keeping up with the chore wheel, and trying to get into nightclubs.",
    posterUrl: "images/2021/What We Do in the Shadows.jpg",
  },
  {
    year: 2021,
    month: "November",
    theme: "Aliens?",
    title: "Contact",
    date: "2021-11-10",
    time: "19:00",
    runtime: "150min",
    rating: "PG",
    releaseYear: 1997,
    description: "Dr. Ellie Arroway, after years of searching, finds conclusive radio proof of extraterrestrial intelligence, sending plans for a mysterious machine.",
    posterUrl: "images/2021/Contact.jpg",
  },
  {
    year: 2021,
    month: "November",
    theme: "Aliens?",
    title: "Arrival",
    date: "2021-11-24",
    time: "19:00",
    runtime: "116min",
    rating: "PG-13",
    releaseYear: 2016,
    description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    posterUrl: "images/2021/Arrival.jpg",
  },
];
