// ============================================================
// RSS_REVIEWS — Generated by scripts/sync-rss-reviews.py
// DO NOT EDIT BY HAND. Regenerated on a schedule from Letterboxd RSS feeds.
// Hand-written reviews live in reviews.js and take precedence on dedup.
// ============================================================

var RSS_REVIEWS = {
  "An Affair to Remember": [
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/an-affair-to-remember/",
      "date": "2025-05-06",
      "text": "very weird to watch after having already seen the original, which is probably a thing no one has been able to say honestly since 1957. <i>Love Affair </i>at least had the courage to put her in the wheelchair on screen",
      "rating": 3.5
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/an-affair-to-remember/",
      "date": "2025-05-06",
      "liked": true,
      "rating": 3.0
    }
  ],
  "Babette's Feast": [
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/babettes-feast/",
      "date": "2025-04-22",
      "text": "is it really an 80s movie without a dash of satanic panic?",
      "rating": 3.5
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/babettes-feast/",
      "date": "2025-04-22",
      "liked": true,
      "rating": 3.5
    }
  ],
  "Before Midnight": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/before-midnight/2/",
      "date": "2026-05-19",
      "text": "It's been years since I last watched this movie, and I've grown in that time. Watching it this time, I was annoyed at how little Jesse and Celine (and I guess, Linklater) had grown up. I still find the movie compelling, but so many of the conversations they have feel juvenile. This is what I imagined adult conversations would be, but now I'm here, and I look at this rut they're in and just think <i>there's so much more out there</i>. They go into a church and still the only thing they can talk about is sex. Call me crazy, but I think there's a lot more to life than that.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/before-midnight/",
      "date": "2026-05-19",
      "text": "did not expect everyone to have an existential crisis about ai destroying creativity at the dinner party in 2013",
      "rating": 3.0
    }
  ],
  "Before Sunset": [
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/before-sunset/",
      "date": "2025-05-20",
      "text": "what another pure and lovely time spying on star-crossed lovers",
      "rating": 4.0
    }
  ],
  "Chicken Run": [
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/chicken-run/",
      "date": "2024-07-30",
      "rewatch": true,
      "liked": true,
      "rating": 3.5
    }
  ],
  "Chronicle": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/chronicle/2/",
      "date": "2026-06-02",
      "text": "I remember this movie being dark, but I think when I was younger watching it, the darkness rolled off of me more. Now I watch it and the stuff with his dad bums me out so much. Obviously it's not meant to be cheerful, but I found watching Andrew's spiral downward far more brutal this time.\n\nStill think the concept is cool and well executed. For good and bad this movie captures the idea of what if a bunch of high school boys got super powers really well.",
      "rewatch": true
    },
    {
      "name": "Jacob L.",
      "letterboxdUrl": "https://letterboxd.com/fluffymastodons/film/chronicle/",
      "date": "2026-06-02",
      "text": "Remember when people were paying $500 for a camcorder?<br />More seriously this movie does so much right, and the way superhero movies have changed since only serves to make it better.",
      "rewatch": true,
      "liked": true,
      "rating": 4.0
    },
    {
      "name": "Joe H.",
      "letterboxdUrl": "https://letterboxd.com/bigjoe0024/film/chronicle/",
      "date": "2026-06-02",
      "text": "The dad deserved worse",
      "liked": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/chronicle/",
      "date": "2026-06-02",
      "text": "I don’t think I want to have the flying dreams anymore",
      "rating": 4.0
    }
  ],
  "Daddy Longlegs": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/daddy-longlegs/2/",
      "date": "2025-09-30",
      "text": "<em>This review may contain spoilers.</em>\n\nThis guy sleeps with a woman, then invites himself and his two kids on a weekend trip with her and her boyfriend, and he faces no consequences.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/daddy-longlegs/",
      "date": "2025-09-30",
      "rating": 3.0
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/daddy-longlegs/1/",
      "date": "2025-09-30",
      "liked": true,
      "rating": 3.0
    }
  ],
  "Dazed and Confused": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/dazed-and-confused/5/",
      "date": "2026-04-21",
      "text": "Ben Affleck and Parker Posey are just downright evil in this movie.\n\nI like Pink though. Even if his motivations are often selfish, he's looking out for people. Same with Jodi. They're not going to break this cycle of hazing, but at least they're nice about it.",
      "rewatch": true
    },
    {
      "name": "Joe H.",
      "letterboxdUrl": "https://letterboxd.com/bigjoe0024/film/dazed-and-confused/",
      "date": "2026-04-21",
      "text": "As someone who was homeschooled...."
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/dazed-and-confused/",
      "date": "2026-04-21",
      "text": "is this the canon origin of alright alright alright",
      "rating": 3.0
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/dazed-and-confused/",
      "date": "2026-04-21",
      "rewatch": true,
      "rating": 3.5
    },
    {
      "name": "Sam H.",
      "letterboxdUrl": "https://letterboxd.com/samsonite49/film/dazed-and-confused/",
      "date": "2026-04-21",
      "text": "I love watching children get beat up for 103 minutes"
    }
  ],
  "Eephus": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/eephus/1/",
      "date": "2026-04-07",
      "text": "The first time I watched this I was focused on the thing that was ending. This time out, I really appreciated the thing that was happening, and the memory it created. Til the end of time those guys will be telling the story of this game.",
      "rewatch": true
    },
    {
      "name": "Joe H.",
      "letterboxdUrl": "https://letterboxd.com/bigjoe0024/film/eephus/",
      "date": "2026-04-07",
      "text": "That one guy reminds me of my coworker Jerry",
      "liked": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/eephus/",
      "date": "2026-04-07",
      "text": "why am I sad that men I’ve never met who aren’t real won’t ever play baseball together again",
      "rating": 3.5
    }
  ],
  "Fantastic Mr. Fox": [
    {
      "name": "Jacob L.",
      "letterboxdUrl": "https://letterboxd.com/fluffymastodons/film/fantastic-mr-fox/",
      "date": "2024-07-16",
      "text": "Somehow I haven't seen this film before today. What a great movie, I regret not having seen it all the way through sooner.",
      "rating": 4.0
    }
  ],
  "Godzilla": [
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/godzilla/",
      "date": "2025-06-03",
      "text": "in this world of cgi, there’s something so charming about watching a movie with practical effects. humans made that. humans said “let’s make a diorama of Tokyo and then make a giant sea lizard that shoot fire and destroys it.”\n\nhumans are great",
      "rating": 3.5
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/godzilla/",
      "date": "2025-06-03",
      "liked": true
    }
  ],
  "Godzilla Minus One": [
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/godzilla-minus-one/",
      "date": "2025-06-17",
      "text": "I came to feel attacked by a sea monster and I’m honestly feeling so emotionally vulnerable right now",
      "rating": 3.5
    }
  ],
  "Inside Man": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/inside-man/1/",
      "date": "2025-11-25",
      "text": "Such a triumphant end to a great year of barn movies.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/inside-man/",
      "date": "2025-11-25",
      "text": "for once a somewhat plausible and realistic unrealistic heist movie",
      "rating": 3.0
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/inside-man/",
      "date": "2025-11-25",
      "liked": true,
      "rating": 3.5
    }
  ],
  "Lilo & Stitch": [
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/lilo-stitch/",
      "date": "2025-07-08",
      "text": "holy crap was I not emotionally prepared for rewatching this as an adult with a greater understanding and compassion for Nani",
      "rewatch": true,
      "liked": true,
      "rating": 4.5
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/lilo-stitch/",
      "date": "2025-07-08",
      "rewatch": true,
      "liked": true,
      "rating": 4.0
    }
  ],
  "Little Shop of Horrors": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/little-shop-of-horrors/1/",
      "date": "2025-10-28",
      "text": "I know every other cameo is bigger and more exciting, but Christopher Guest steals the whole movie with his one scene.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/little-shop-of-horrors/",
      "date": "2025-10-28",
      "text": "oh so this is where the idea for Larry Boy and the Rumor Weed came from\n\nchildhood ruined, 5 stars",
      "liked": true,
      "rating": 5.0
    }
  ],
  "Moonrise Kingdom": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/moonrise-kingdom/4/",
      "date": "2025-08-26",
      "text": "It's incredible that Wes captures what it felt like to be a kid in a movie that's engaging for adults. Call them precocious all you want, but I would sit there as a kid with my friends and devise these exact sorts of schemes, thinking we were the smartest people out there. We just never had the follow through to actually do them.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/moonrise-kingdom/",
      "date": "2025-08-26",
      "text": "I felt warm and fuzzy the entire time. lovely",
      "liked": true,
      "rating": 4.5
    }
  ],
  "Paths of Glory": [
    {
      "name": "Andrew A.",
      "letterboxdUrl": "https://letterboxd.com/andrewacebo/film/paths-of-glory/",
      "date": "2023-11-14",
      "liked": true,
      "rating": 4.0
    }
  ],
  "Patty Hearst": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/patty-hearst/1/",
      "date": "2025-11-11",
      "text": "Had a good time watching this again post One Battle After Another.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/patty-hearst/",
      "date": "2025-11-11",
      "text": "artistic a+ love that all the scenes where she’s blindfolded are visually trippy af\n\nbut tbh story was hard to follow and i was one of the only people on the room who knew the story",
      "rating": 3.0
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/patty-hearst/",
      "date": "2025-11-11",
      "liked": true,
      "rating": 3.5
    }
  ],
  "Phantom of the Paradise": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/phantom-of-the-paradise/1/",
      "date": "2025-10-17",
      "text": "Carburetors man, that’s what life’s all about.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/phantom-of-the-paradise/",
      "date": "2025-10-17",
      "text": "what the hell justice for beef",
      "rating": 4.0
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/phantom-of-the-paradise/",
      "date": "2025-10-17",
      "liked": true,
      "rating": 4.0
    }
  ],
  "Sing Street": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/sing-street/1/",
      "date": "2025-08-12",
      "text": "I watch a movie like this and think <i>I should have been in a band when I was in high school in Dublin in the 80s</i>.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/sing-street/",
      "date": "2025-08-12",
      "text": "this was just the movie I needed. boys in a band being silly and emo and hopeful",
      "liked": true,
      "rating": 4.0
    }
  ],
  "Sky High": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/sky-high-2005/",
      "date": "2026-06-16",
      "text": "It's a rom-com in superhero clothing, so for a kid who felt insecure about liking rom-coms, it's no wonder I liked it so much.",
      "rewatch": true
    },
    {
      "name": "Joe H.",
      "letterboxdUrl": "https://letterboxd.com/bigjoe0024/film/sky-high-2005/",
      "date": "2026-06-16",
      "text": "<a href=\"https://youtu.be/hcr02D5D_Iw\" rel=\"nofollow\">youtu.be/hcr02D5D_Iw</a>",
      "liked": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/sky-high-2005/",
      "date": "2026-06-16",
      "text": "it’s always a great time when a childhood favorite holds up and exceeds my memories",
      "rewatch": true,
      "liked": true,
      "rating": 3.5
    }
  ],
  "The Awful Truth": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/the-awful-truth/1/",
      "date": "2026-05-05",
      "text": "Few things are more engaging than Irene Dunne and Cary Grant politely ridiculing each other. This movie just rules. Hearing the crowd roar with laughter during the sequence with the hats brought me so much joy. So glad I get to share this with people.",
      "rewatch": true
    },
    {
      "name": "Joe H.",
      "letterboxdUrl": "https://letterboxd.com/bigjoe0024/film/the-awful-truth/",
      "date": "2026-05-05",
      "text": "This movie is like if the pina colada song was a movie...\n\nI hate that song."
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/the-awful-truth/",
      "date": "2026-05-05",
      "text": "these two’s rebounds give the concept of 90 day fiancé(e) quite a run for its money\n\nalso I’m a sucker for anyone who gives a dog a human name and mr. smith may be the most anthropomorphic yet still overall canine human-named dog ever. genius.",
      "rating": 3.5
    }
  ],
  "The Florida Project": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/the-florida-project/1/",
      "date": "2025-09-16",
      "text": "My recollection was that Halley was a more sympathetic character. The movie doesn't need her to be for it to work though. So often this sort of narrative portrays someone who is truly trying their best, but Halley isn't . She's just existing in the only way she knows how.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/the-florida-project/",
      "date": "2025-09-16",
      "text": "what a ride to go into completely blind",
      "rating": 3.0
    }
  ],
  "The Taste of Things": [
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/the-taste-of-things/",
      "date": "2025-04-01",
      "text": "2/3 cooking asmr\n\n1/3 daring to ask “what if the love language of acts of service was specifically the act of serving pretentious French cuisine?”",
      "rating": 2.0
    }
  ],
  "Treasure Planet": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/treasure-planet/1/",
      "date": "2025-07-22",
      "text": "Did not appreciate how hard the \"camera\" goes in some of these scenes as a kid. Treasure Planet walked so Tintin could run.",
      "rewatch": true
    },
    {
      "name": "Morgan M.",
      "letterboxdUrl": "https://letterboxd.com/ayoitsmo/film/treasure-planet/",
      "date": "2025-07-22",
      "text": "fantastic story but something about the 2d/3d simultaneous animation breaks my brain",
      "rating": 3.5
    }
  ]
};
