// ============================================================
// RSS_REVIEWS — Generated by scripts/sync-rss-reviews.py
// DO NOT EDIT BY HAND. Regenerated on a schedule from Letterboxd RSS feeds.
// Hand-written reviews live in reviews.js and take precedence on dedup.
// ============================================================

var RSS_REVIEWS = {
  "An Affair to Remember": [
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/an-affair-to-remember/",
      "date": "2025-05-06",
      "liked": true,
      "rating": 3.0
    }
  ],
  "Babette's Feast": [
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/babettes-feast/",
      "date": "2025-04-22",
      "liked": true,
      "rating": 3.5
    }
  ],
  "Chicken Run": [
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/chicken-run/",
      "date": "2024-07-30",
      "rewatch": true,
      "liked": true,
      "rating": 3.5
    }
  ],
  "Daddy Longlegs": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/daddy-longlegs/2/",
      "date": "2025-09-30",
      "text": "<em>This review may contain spoilers.</em>\n\nThis guy sleeps with a woman, then invites himself and his two kids on a weekend trip with her and her boyfriend, and he faces no consequences.",
      "rewatch": true
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/daddy-longlegs/1/",
      "date": "2025-09-30",
      "liked": true,
      "rating": 3.0
    }
  ],
  "Dazed and Confused": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/dazed-and-confused/5/",
      "date": "2026-04-21",
      "text": "Ben Affleck and Parker Posey are just downright evil in this movie.\n\nI like Pink though. Even if his motivations are often selfish, he's looking out for people. Same with Jodi. They're not going to break this cycle of hazing, but at least they're nice about it.",
      "rewatch": true
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/dazed-and-confused/",
      "date": "2026-04-21",
      "rewatch": true,
      "rating": 3.5
    }
  ],
  "Eephus": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/eephus/1/",
      "date": "2026-04-07",
      "text": "The first time I watched this I was focused on the thing that was ending. This time out, I really appreciated the thing that was happening, and the memory it created. Til the end of time those guys will be telling the story of this game.",
      "rewatch": true
    }
  ],
  "Fantastic Mr. Fox": [
    {
      "name": "Jacob L.",
      "letterboxdUrl": "https://letterboxd.com/fluffymastodons/film/fantastic-mr-fox/",
      "date": "2024-07-16",
      "text": "Somehow I haven't seen this film before today. What a great movie, I regret not having seen it all the way through sooner.",
      "rating": 4.0
    }
  ],
  "Godzilla": [
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/godzilla/",
      "date": "2025-06-03",
      "liked": true
    }
  ],
  "Inside Man": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/inside-man/1/",
      "date": "2025-11-25",
      "text": "Such a triumphant end to a great year of barn movies.",
      "rewatch": true
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/inside-man/",
      "date": "2025-11-25",
      "liked": true,
      "rating": 3.5
    }
  ],
  "Lilo & Stitch": [
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/lilo-stitch/",
      "date": "2025-07-08",
      "rewatch": true,
      "liked": true,
      "rating": 4.0
    }
  ],
  "Little Shop of Horrors": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/little-shop-of-horrors/1/",
      "date": "2025-10-28",
      "text": "I know every other cameo is bigger and more exciting, but Christopher Guest steals the whole movie with his one scene.",
      "rewatch": true
    }
  ],
  "Moonrise Kingdom": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/moonrise-kingdom/4/",
      "date": "2025-08-26",
      "text": "It's incredible that Wes captures what it felt like to be a kid in a movie that's engaging for adults. Call them precocious all you want, but I would sit there as a kid with my friends and devise these exact sorts of schemes, thinking we were the smartest people out there. We just never had the follow through to actually do them.",
      "rewatch": true
    }
  ],
  "Paths of Glory": [
    {
      "name": "Andrew A.",
      "letterboxdUrl": "https://letterboxd.com/andrewacebo/film/paths-of-glory/",
      "date": "2023-11-14",
      "liked": true,
      "rating": 4.0
    }
  ],
  "Patty Hearst": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/patty-hearst/1/",
      "date": "2025-11-11",
      "text": "Had a good time watching this again post One Battle After Another.",
      "rewatch": true
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/patty-hearst/",
      "date": "2025-11-11",
      "liked": true,
      "rating": 3.5
    }
  ],
  "Phantom of the Paradise": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/phantom-of-the-paradise/1/",
      "date": "2025-10-17",
      "text": "Carburetors man, that’s what life’s all about.",
      "rewatch": true
    },
    {
      "name": "Nathan H.",
      "letterboxdUrl": "https://letterboxd.com/njh20/film/phantom-of-the-paradise/",
      "date": "2025-10-17",
      "liked": true,
      "rating": 4.0
    }
  ],
  "Sing Street": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/sing-street/1/",
      "date": "2025-08-12",
      "text": "I watch a movie like this and think <i>I should have been in a band when I was in high school in Dublin in the 80s</i>.",
      "rewatch": true
    }
  ],
  "The Florida Project": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/the-florida-project/1/",
      "date": "2025-09-16",
      "text": "My recollection was that Halley was a more sympathetic character. The movie doesn't need her to be for it to work though. So often this sort of narrative portrays someone who is truly trying their best, but Halley isn't . She's just existing in the only way she knows how.",
      "rewatch": true
    }
  ],
  "Treasure Planet": [
    {
      "name": "Dylan W.",
      "letterboxdUrl": "https://letterboxd.com/djweaver29/film/treasure-planet/1/",
      "date": "2025-07-22",
      "text": "Did not appreciate how hard the \"camera\" goes in some of these scenes as a kid. Treasure Planet walked so Tintin could run.",
      "rewatch": true
    }
  ]
};
